wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1674954092.945226
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.9.13
      5: 0.13.4
      8:
      - 5
